[project]
name = "quiz-capstone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Bia", email = "srbia2009@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "streamlit>=1.64.0",
]

[project.scripts]
quiz-capstone = "quiz_capstone:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
